-- User-defined categories with name and color
create table if not exists categories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  color text not null,
  created_at timestamptz default now() not null,
  unique (user_id, name)
);

alter table categories enable row level security;

create policy "Users can read own categories"
  on categories for select
  using (auth.uid() = user_id);

create policy "Users can create own categories"
  on categories for insert
  with check (auth.uid() = user_id);

create policy "Users can update own categories"
  on categories for update
  using (auth.uid() = user_id);

create policy "Users can delete own categories"
  on categories for delete
  using (auth.uid() = user_id);
